name: Test Codespace Environment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-codespace:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Node.js
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install --lts
        nvm use --lts
        
    - name: Install cli-zy
      run: npm install -g .
      
    - name: Test cli-zy setup
      run: cli-zy setup 
